package com.crm.wcx.dao;

import com.crm.wcx.entity.CustomerTransfer;
import com.crm.wcx.entity.CustomerTransferExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustomerTransferMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_transfer
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    long countByExample(CustomerTransferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_transfer
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int deleteByExample(CustomerTransferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_transfer
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_transfer
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int insert(CustomerTransfer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_transfer
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int insertSelective(CustomerTransfer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_transfer
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    List<CustomerTransfer> selectByExample(CustomerTransferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_transfer
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    CustomerTransfer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_transfer
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int updateByExampleSelective(@Param("record") CustomerTransfer record, @Param("example") CustomerTransferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_transfer
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int updateByExample(@Param("record") CustomerTransfer record, @Param("example") CustomerTransferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_transfer
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int updateByPrimaryKeySelective(CustomerTransfer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_transfer
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int updateByPrimaryKey(CustomerTransfer record);
}