package com.crm.wcx.dao;

import com.crm.wcx.entity.CustomerLoss;
import com.crm.wcx.entity.CustomerLossExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustomerLossMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_loss
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    long countByExample(CustomerLossExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_loss
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int deleteByExample(CustomerLossExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_loss
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_loss
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int insert(CustomerLoss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_loss
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int insertSelective(CustomerLoss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_loss
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    List<CustomerLoss> selectByExample(CustomerLossExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_loss
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    CustomerLoss selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_loss
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int updateByExampleSelective(@Param("record") CustomerLoss record, @Param("example") CustomerLossExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_loss
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int updateByExample(@Param("record") CustomerLoss record, @Param("example") CustomerLossExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_loss
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int updateByPrimaryKeySelective(CustomerLoss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_loss
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int updateByPrimaryKey(CustomerLoss record);
}