package com.crm.wcx.dao;

import com.crm.wcx.entity.DictionaryItem;
import com.crm.wcx.entity.DictionaryItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DictionaryItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_item
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    long countByExample(DictionaryItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_item
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int deleteByExample(DictionaryItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_item
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_item
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int insert(DictionaryItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_item
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int insertSelective(DictionaryItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_item
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    List<DictionaryItem> selectByExample(DictionaryItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_item
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    DictionaryItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_item
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int updateByExampleSelective(@Param("record") DictionaryItem record, @Param("example") DictionaryItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_item
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int updateByExample(@Param("record") DictionaryItem record, @Param("example") DictionaryItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_item
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int updateByPrimaryKeySelective(DictionaryItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_item
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int updateByPrimaryKey(DictionaryItem record);
}