package com.crm.wcx.dao;

import com.crm.wcx.entity.DictionaryType;
import com.crm.wcx.entity.DictionaryTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DictionaryTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_type
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    long countByExample(DictionaryTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_type
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int deleteByExample(DictionaryTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_type
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_type
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int insert(DictionaryType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_type
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int insertSelective(DictionaryType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_type
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    List<DictionaryType> selectByExample(DictionaryTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_type
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    DictionaryType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_type
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int updateByExampleSelective(@Param("record") DictionaryType record, @Param("example") DictionaryTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_type
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int updateByExample(@Param("record") DictionaryType record, @Param("example") DictionaryTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_type
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int updateByPrimaryKeySelective(DictionaryType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_type
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int updateByPrimaryKey(DictionaryType record);
}