package com.crm.wcx.dao;

import com.crm.wcx.entity.FollowUp;
import com.crm.wcx.entity.FollowUpExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FollowUpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow_up
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    long countByExample(FollowUpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow_up
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int deleteByExample(FollowUpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow_up
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow_up
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int insert(FollowUp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow_up
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int insertSelective(FollowUp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow_up
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    List<FollowUp> selectByExampleWithBLOBs(FollowUpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow_up
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    List<FollowUp> selectByExample(FollowUpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow_up
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    FollowUp selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow_up
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int updateByExampleSelective(@Param("record") FollowUp record, @Param("example") FollowUpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow_up
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") FollowUp record, @Param("example") FollowUpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow_up
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int updateByExample(@Param("record") FollowUp record, @Param("example") FollowUpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow_up
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int updateByPrimaryKeySelective(FollowUp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow_up
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(FollowUp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow_up
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int updateByPrimaryKey(FollowUp record);
}