package com.crm.wcx.dao;

import com.crm.wcx.entity.Linkman;
import com.crm.wcx.entity.LinkmanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LinkmanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkman
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    long countByExample(LinkmanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkman
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int deleteByExample(LinkmanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkman
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkman
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int insert(Linkman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkman
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int insertSelective(Linkman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkman
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    List<Linkman> selectByExample(LinkmanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkman
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    Linkman selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkman
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int updateByExampleSelective(@Param("record") Linkman record, @Param("example") LinkmanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkman
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int updateByExample(@Param("record") Linkman record, @Param("example") LinkmanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkman
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int updateByPrimaryKeySelective(Linkman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkman
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int updateByPrimaryKey(Linkman record);
}