package com.crm.wcx.dao;

import com.crm.wcx.entity.LoggingEventException;
import com.crm.wcx.entity.LoggingEventExceptionExample;
import com.crm.wcx.entity.LoggingEventExceptionKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LoggingEventExceptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logging_event_exception
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    long countByExample(LoggingEventExceptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logging_event_exception
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int deleteByExample(LoggingEventExceptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logging_event_exception
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int deleteByPrimaryKey(LoggingEventExceptionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logging_event_exception
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int insert(LoggingEventException record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logging_event_exception
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int insertSelective(LoggingEventException record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logging_event_exception
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    List<LoggingEventException> selectByExample(LoggingEventExceptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logging_event_exception
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    LoggingEventException selectByPrimaryKey(LoggingEventExceptionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logging_event_exception
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int updateByExampleSelective(@Param("record") LoggingEventException record, @Param("example") LoggingEventExceptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logging_event_exception
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int updateByExample(@Param("record") LoggingEventException record, @Param("example") LoggingEventExceptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logging_event_exception
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int updateByPrimaryKeySelective(LoggingEventException record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logging_event_exception
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int updateByPrimaryKey(LoggingEventException record);
}