package com.crm.wcx.dao;

import com.crm.wcx.entity.SaleOpportunity;
import com.crm.wcx.entity.SaleOpportunityExample;
import com.crm.wcx.entity.SaleOpportunityWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SaleOpportunityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_opportunity
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    long countByExample(SaleOpportunityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_opportunity
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int deleteByExample(SaleOpportunityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_opportunity
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_opportunity
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int insert(SaleOpportunityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_opportunity
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int insertSelective(SaleOpportunityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_opportunity
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    List<SaleOpportunityWithBLOBs> selectByExampleWithBLOBs(SaleOpportunityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_opportunity
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    List<SaleOpportunity> selectByExample(SaleOpportunityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_opportunity
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    SaleOpportunityWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_opportunity
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int updateByExampleSelective(@Param("record") SaleOpportunityWithBLOBs record, @Param("example") SaleOpportunityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_opportunity
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") SaleOpportunityWithBLOBs record, @Param("example") SaleOpportunityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_opportunity
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int updateByExample(@Param("record") SaleOpportunity record, @Param("example") SaleOpportunityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_opportunity
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int updateByPrimaryKeySelective(SaleOpportunityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_opportunity
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(SaleOpportunityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_opportunity
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int updateByPrimaryKey(SaleOpportunity record);
}