package com.crm.wcx.dao;

import com.crm.wcx.entity.ServiceTransfer;
import com.crm.wcx.entity.ServiceTransferExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ServiceTransferMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_transfer
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    long countByExample(ServiceTransferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_transfer
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int deleteByExample(ServiceTransferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_transfer
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_transfer
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int insert(ServiceTransfer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_transfer
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int insertSelective(ServiceTransfer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_transfer
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    List<ServiceTransfer> selectByExample(ServiceTransferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_transfer
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    ServiceTransfer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_transfer
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int updateByExampleSelective(@Param("record") ServiceTransfer record, @Param("example") ServiceTransferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_transfer
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int updateByExample(@Param("record") ServiceTransfer record, @Param("example") ServiceTransferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_transfer
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int updateByPrimaryKeySelective(ServiceTransfer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_transfer
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    int updateByPrimaryKey(ServiceTransfer record);
}