package com.crm.wcx.entity;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Date;

import com.crm.wcx.utils.LocalDateTimeUtil;

public class CustomerLoss {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_loss.id
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_loss.customer_id
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    private Integer customerId;
    
    private Customer customer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_loss.last_order_time
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    private LocalDateTime lastOrderTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_loss.measure
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    private String measure;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_loss.measure_append
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    private String measureAppend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_loss.loss_date
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    private LocalDateTime lossDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_loss.reason
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_loss.status
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_loss.id
     *
     * @return the value of customer_loss.id
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_loss.id
     *
     * @param id the value for customer_loss.id
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_loss.customer_id
     *
     * @return the value of customer_loss.customer_id
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_loss.customer_id
     *
     * @param customerId the value for customer_loss.customer_id
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_loss.last_order_time
     *
     * @return the value of customer_loss.last_order_time
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public String getLastOrderTime() {
        return LocalDateTimeUtil.formatTime(lastOrderTime, "yyyy-MM-dd");
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_loss.last_order_time
     *
     * @param lastOrderTime the value for customer_loss.last_order_time
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public void setLastOrderTime(LocalDateTime lastOrderTime) {
        this.lastOrderTime = lastOrderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_loss.measure
     *
     * @return the value of customer_loss.measure
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public String getMeasure() {
        return measure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_loss.measure
     *
     * @param measure the value for customer_loss.measure
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public void setMeasure(String measure) {
        this.measure = measure == null ? null : measure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_loss.measure_append
     *
     * @return the value of customer_loss.measure_append
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public String getMeasureAppend() {
        return measureAppend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_loss.measure_append
     *
     * @param measureAppend the value for customer_loss.measure_append
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public void setMeasureAppend(String measureAppend) {
        this.measureAppend = measureAppend == null ? null : measureAppend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_loss.loss_date
     *
     * @return the value of customer_loss.loss_date
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public LocalDateTime getLossDate() {
        return lossDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_loss.loss_date
     *
     * @param lossDate the value for customer_loss.loss_date
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public void setLossDate(LocalDateTime lossDate) {
        this.lossDate = lossDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_loss.reason
     *
     * @return the value of customer_loss.reason
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_loss.reason
     *
     * @param reason the value for customer_loss.reason
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_loss.status
     *
     * @return the value of customer_loss.status
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_loss.status
     *
     * @param status the value for customer_loss.status
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

	public Customer getCustomer() {
		return customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}
}