package com.crm.wcx.entity;

import java.util.List;

public class DictionaryType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_type.id
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_type.name
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    private String name;
    
    
    private List<DictionaryItem> dictionaryItems;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_type.id
     *
     * @return the value of dictionary_type.id
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_type.id
     *
     * @param id the value for dictionary_type.id
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_type.name
     *
     * @return the value of dictionary_type.name
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_type.name
     *
     * @param name the value for dictionary_type.name
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

	public List<DictionaryItem> getDictionaryItems() {
		return dictionaryItems;
	}

	public void setDictionaryItems(List<DictionaryItem> dictionaryItems) {
		this.dictionaryItems = dictionaryItems;
	}
}