package com.crm.wcx.entity;

public class OrderItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.id
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.num
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.unit
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.unit_price
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    private Double unitPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.price
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.orders_id
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    private Integer ordersId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.product_id
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    private Integer productId;
    
    
    private Product product;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.id
     *
     * @return the value of order_item.id
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.id
     *
     * @param id the value for order_item.id
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.num
     *
     * @return the value of order_item.num
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.num
     *
     * @param num the value for order_item.num
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.unit
     *
     * @return the value of order_item.unit
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.unit
     *
     * @param unit the value for order_item.unit
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.unit_price
     *
     * @return the value of order_item.unit_price
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public Double getUnitPrice() {
        return unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.unit_price
     *
     * @param unitPrice the value for order_item.unit_price
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public void setUnitPrice(Double unitPrice) {
        this.unitPrice = unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.price
     *
     * @return the value of order_item.price
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.price
     *
     * @param price the value for order_item.price
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.orders_id
     *
     * @return the value of order_item.orders_id
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public Integer getOrdersId() {
        return ordersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.orders_id
     *
     * @param ordersId the value for order_item.orders_id
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public void setOrdersId(Integer ordersId) {
        this.ordersId = ordersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.product_id
     *
     * @return the value of order_item.product_id
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.product_id
     *
     * @param productId the value for order_item.product_id
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

	public Product getProduct() {
		return product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}
}