package com.crm.wcx.entity;

import java.time.LocalDateTime;
import java.util.Date;

import com.crm.wcx.utils.LocalDateTimeUtil;

public class ServiceTransfer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_transfer.id
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_transfer.service_id
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    private Integer serviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_transfer.old_manager_id
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    private Integer oldManagerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_transfer.new_manager_id
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    private Integer newManagerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_transfer.time
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    private LocalDateTime time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_transfer.reason
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    private String reason;
    
    
    private User oldManager;
    
    
    private User newManager;
    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_transfer.id
     *
     * @return the value of service_transfer.id
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_transfer.id
     *
     * @param id the value for service_transfer.id
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_transfer.service_id
     *
     * @return the value of service_transfer.service_id
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public Integer getServiceId() {
        return serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_transfer.service_id
     *
     * @param serviceId the value for service_transfer.service_id
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public void setServiceId(Integer serviceId) {
        this.serviceId = serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_transfer.old_manager_id
     *
     * @return the value of service_transfer.old_manager_id
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public Integer getOldManagerId() {
        return oldManagerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_transfer.old_manager_id
     *
     * @param oldManagerId the value for service_transfer.old_manager_id
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public void setOldManagerId(Integer oldManagerId) {
        this.oldManagerId = oldManagerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_transfer.new_manager_id
     *
     * @return the value of service_transfer.new_manager_id
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public Integer getNewManagerId() {
        return newManagerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_transfer.new_manager_id
     *
     * @param newManagerId the value for service_transfer.new_manager_id
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public void setNewManagerId(Integer newManagerId) {
        this.newManagerId = newManagerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_transfer.time
     *
     * @return the value of service_transfer.time
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public String getTime() {
        return LocalDateTimeUtil.formatTime(time, "yyyy-MM-dd HH:mm:ss");
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_transfer.time
     *
     * @param localDateTime the value for service_transfer.time
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public void setTime(LocalDateTime localDateTime) {
        this.time = localDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_transfer.reason
     *
     * @return the value of service_transfer.reason
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_transfer.reason
     *
     * @param reason the value for service_transfer.reason
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

	public User getOldManager() {
		return oldManager;
	}

	public void setOldManager(User oldManager) {
		this.oldManager = oldManager;
	}

	public User getNewManager() {
		return newManager;
	}

	public void setNewManager(User newManager) {
		this.newManager = newManager;
	}
}