package com.crm.wcx.entity;

public class ServiceWithBLOBs extends Service {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.request
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    private String request;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.handle_content
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    private String handleContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.handle_result
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    private String handleResult;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.request
     *
     * @return the value of service.request
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public String getRequest() {
        return request;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.request
     *
     * @param request the value for service.request
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public void setRequest(String request) {
        this.request = request == null ? null : request.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.handle_content
     *
     * @return the value of service.handle_content
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public String getHandleContent() {
        return handleContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.handle_content
     *
     * @param handleContent the value for service.handle_content
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public void setHandleContent(String handleContent) {
        this.handleContent = handleContent == null ? null : handleContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.handle_result
     *
     * @return the value of service.handle_result
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public String getHandleResult() {
        return handleResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.handle_result
     *
     * @param handleResult the value for service.handle_result
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public void setHandleResult(String handleResult) {
        this.handleResult = handleResult == null ? null : handleResult.trim();
    }
}