package com.crm.wcx.entity;

import java.time.LocalDateTime;
import java.util.Date;

import com.crm.wcx.utils.LocalDateTimeUtil;

public class Service {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.id
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.type
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.general
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    private String general;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.customer_id
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    private Integer customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.emergency
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    private String emergency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.phone_number
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    private String phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.status
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.creater
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    private Integer creater;
    
    
    private User createrObject;
    
    
    private User handlerObject;
    
    
    private Customer customer;
    

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.create_date
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    private LocalDateTime createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.handler
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    private Integer handler;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.handler_time
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    private Date handlerTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.degree
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    private String degree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.delete_status
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    private Integer deleteStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.id
     *
     * @return the value of service.id
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.id
     *
     * @param id the value for service.id
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.type
     *
     * @return the value of service.type
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.type
     *
     * @param type the value for service.type
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.general
     *
     * @return the value of service.general
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public String getGeneral() {
        return general;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.general
     *
     * @param general the value for service.general
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public void setGeneral(String general) {
        this.general = general == null ? null : general.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.customer_id
     *
     * @return the value of service.customer_id
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.customer_id
     *
     * @param customerId the value for service.customer_id
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.emergency
     *
     * @return the value of service.emergency
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public String getEmergency() {
        return emergency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.emergency
     *
     * @param emergency the value for service.emergency
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public void setEmergency(String emergency) {
        this.emergency = emergency == null ? null : emergency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.phone_number
     *
     * @return the value of service.phone_number
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.phone_number
     *
     * @param phoneNumber the value for service.phone_number
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.status
     *
     * @return the value of service.status
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.status
     *
     * @param status the value for service.status
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.creater
     *
     * @return the value of service.creater
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public Integer getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.creater
     *
     * @param creater the value for service.creater
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public void setCreater(Integer creater) {
        this.creater = creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.create_date
     *
     * @return the value of service.create_date
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public String getCreateDate() {
    	return LocalDateTimeUtil.formatTime(createDate, "yyyy-MM-dd HH:mm:ss");
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.create_date
     *
     * @param createDate the value for service.create_date
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public void setCreateDate(LocalDateTime createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.handler
     *
     * @return the value of service.handler
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public Integer getHandler() {
        return handler;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.handler
     *
     * @param handler the value for service.handler
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public void setHandler(Integer handler) {
        this.handler = handler;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.handler_time
     *
     * @return the value of service.handler_time
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public Date getHandlerTime() {
        return handlerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.handler_time
     *
     * @param handlerTime the value for service.handler_time
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public void setHandlerTime(Date handlerTime) {
        this.handlerTime = handlerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.degree
     *
     * @return the value of service.degree
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public String getDegree() {
        return degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.degree
     *
     * @param degree the value for service.degree
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public void setDegree(String degree) {
        this.degree = degree == null ? null : degree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.delete_status
     *
     * @return the value of service.delete_status
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public Integer getDeleteStatus() {
        return deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.delete_status
     *
     * @param deleteStatus the value for service.delete_status
     *
     * @mbg.generated Thu Nov 08 12:22:40 CST 2018
     */
    public void setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

	public User getCreaterObject() {
		return createrObject;
	}

	public void setCreaterObject(User createrObject) {
		this.createrObject = createrObject;
	}

	public User getHandlerObject() {
		return handlerObject;
	}

	public void setHandlerObject(User handlerObject) {
		this.handlerObject = handlerObject;
	}

	public Customer getCustomer() {
		return customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}
}