package com.crm.wcx.entity;

import java.util.Date;

public class Customer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.id
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.name
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.type
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.level
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private String level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.status
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.credit
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private String credit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.area
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private String area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.company_address
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private String companyAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.company_phone
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private String companyPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.post_code
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private String postCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.fax_address
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private String faxAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.company_website
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private String companyWebsite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.license_number
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private String licenseNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.corporation
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private String corporation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.annual_sale
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private Double annualSale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.deposit_bank
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private String depositBank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.bank_account
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private String bankAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.land_tax_number
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private String landTaxNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.national_tax_number
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private String nationalTaxNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.source
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.description
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.maturity
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private String maturity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.document
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private String document;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.delete_status
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private Integer deleteStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.manager_id
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private Integer managerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.product_id
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.creater
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.create_time
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.id
     *
     * @return the value of customer.id
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.id
     *
     * @param id the value for customer.id
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.name
     *
     * @return the value of customer.name
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.name
     *
     * @param name the value for customer.name
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.type
     *
     * @return the value of customer.type
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.type
     *
     * @param type the value for customer.type
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.level
     *
     * @return the value of customer.level
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.level
     *
     * @param level the value for customer.level
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.status
     *
     * @return the value of customer.status
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.status
     *
     * @param status the value for customer.status
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.credit
     *
     * @return the value of customer.credit
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public String getCredit() {
        return credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.credit
     *
     * @param credit the value for customer.credit
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setCredit(String credit) {
        this.credit = credit == null ? null : credit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.area
     *
     * @return the value of customer.area
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.area
     *
     * @param area the value for customer.area
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.company_address
     *
     * @return the value of customer.company_address
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public String getCompanyAddress() {
        return companyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.company_address
     *
     * @param companyAddress the value for customer.company_address
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setCompanyAddress(String companyAddress) {
        this.companyAddress = companyAddress == null ? null : companyAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.company_phone
     *
     * @return the value of customer.company_phone
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public String getCompanyPhone() {
        return companyPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.company_phone
     *
     * @param companyPhone the value for customer.company_phone
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setCompanyPhone(String companyPhone) {
        this.companyPhone = companyPhone == null ? null : companyPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.post_code
     *
     * @return the value of customer.post_code
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.post_code
     *
     * @param postCode the value for customer.post_code
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode == null ? null : postCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.fax_address
     *
     * @return the value of customer.fax_address
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public String getFaxAddress() {
        return faxAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.fax_address
     *
     * @param faxAddress the value for customer.fax_address
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setFaxAddress(String faxAddress) {
        this.faxAddress = faxAddress == null ? null : faxAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.company_website
     *
     * @return the value of customer.company_website
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public String getCompanyWebsite() {
        return companyWebsite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.company_website
     *
     * @param companyWebsite the value for customer.company_website
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setCompanyWebsite(String companyWebsite) {
        this.companyWebsite = companyWebsite == null ? null : companyWebsite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.license_number
     *
     * @return the value of customer.license_number
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public String getLicenseNumber() {
        return licenseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.license_number
     *
     * @param licenseNumber the value for customer.license_number
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setLicenseNumber(String licenseNumber) {
        this.licenseNumber = licenseNumber == null ? null : licenseNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.corporation
     *
     * @return the value of customer.corporation
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public String getCorporation() {
        return corporation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.corporation
     *
     * @param corporation the value for customer.corporation
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setCorporation(String corporation) {
        this.corporation = corporation == null ? null : corporation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.annual_sale
     *
     * @return the value of customer.annual_sale
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public Double getAnnualSale() {
        return annualSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.annual_sale
     *
     * @param annualSale the value for customer.annual_sale
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setAnnualSale(Double annualSale) {
        this.annualSale = annualSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.deposit_bank
     *
     * @return the value of customer.deposit_bank
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public String getDepositBank() {
        return depositBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.deposit_bank
     *
     * @param depositBank the value for customer.deposit_bank
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setDepositBank(String depositBank) {
        this.depositBank = depositBank == null ? null : depositBank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.bank_account
     *
     * @return the value of customer.bank_account
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public String getBankAccount() {
        return bankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.bank_account
     *
     * @param bankAccount the value for customer.bank_account
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setBankAccount(String bankAccount) {
        this.bankAccount = bankAccount == null ? null : bankAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.land_tax_number
     *
     * @return the value of customer.land_tax_number
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public String getLandTaxNumber() {
        return landTaxNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.land_tax_number
     *
     * @param landTaxNumber the value for customer.land_tax_number
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setLandTaxNumber(String landTaxNumber) {
        this.landTaxNumber = landTaxNumber == null ? null : landTaxNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.national_tax_number
     *
     * @return the value of customer.national_tax_number
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public String getNationalTaxNumber() {
        return nationalTaxNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.national_tax_number
     *
     * @param nationalTaxNumber the value for customer.national_tax_number
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setNationalTaxNumber(String nationalTaxNumber) {
        this.nationalTaxNumber = nationalTaxNumber == null ? null : nationalTaxNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.source
     *
     * @return the value of customer.source
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.source
     *
     * @param source the value for customer.source
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.description
     *
     * @return the value of customer.description
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.description
     *
     * @param description the value for customer.description
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.maturity
     *
     * @return the value of customer.maturity
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public String getMaturity() {
        return maturity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.maturity
     *
     * @param maturity the value for customer.maturity
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setMaturity(String maturity) {
        this.maturity = maturity == null ? null : maturity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.document
     *
     * @return the value of customer.document
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public String getDocument() {
        return document;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.document
     *
     * @param document the value for customer.document
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setDocument(String document) {
        this.document = document == null ? null : document.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.delete_status
     *
     * @return the value of customer.delete_status
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public Integer getDeleteStatus() {
        return deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.delete_status
     *
     * @param deleteStatus the value for customer.delete_status
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.manager_id
     *
     * @return the value of customer.manager_id
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public Integer getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.manager_id
     *
     * @param managerId the value for customer.manager_id
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setManagerId(Integer managerId) {
        this.managerId = managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.product_id
     *
     * @return the value of customer.product_id
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.product_id
     *
     * @param productId the value for customer.product_id
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.creater
     *
     * @return the value of customer.creater
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.creater
     *
     * @param creater the value for customer.creater
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.create_time
     *
     * @return the value of customer.create_time
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.create_time
     *
     * @param createTime the value for customer.create_time
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}