package com.crm.wcx.entity;

import java.util.Date;

public class CustomerCare {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_care.id
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_care.linkman_id
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private Integer linkmanId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_care.birthday
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_care.time
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_care.detail
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private String detail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_care.type
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_care.status
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_care.feedback
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private String feedback;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_care.create_time
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_care.manager_id
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private Integer managerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_care.id
     *
     * @return the value of customer_care.id
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_care.id
     *
     * @param id the value for customer_care.id
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_care.linkman_id
     *
     * @return the value of customer_care.linkman_id
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public Integer getLinkmanId() {
        return linkmanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_care.linkman_id
     *
     * @param linkmanId the value for customer_care.linkman_id
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setLinkmanId(Integer linkmanId) {
        this.linkmanId = linkmanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_care.birthday
     *
     * @return the value of customer_care.birthday
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_care.birthday
     *
     * @param birthday the value for customer_care.birthday
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_care.time
     *
     * @return the value of customer_care.time
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_care.time
     *
     * @param time the value for customer_care.time
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_care.detail
     *
     * @return the value of customer_care.detail
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_care.detail
     *
     * @param detail the value for customer_care.detail
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_care.type
     *
     * @return the value of customer_care.type
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_care.type
     *
     * @param type the value for customer_care.type
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_care.status
     *
     * @return the value of customer_care.status
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_care.status
     *
     * @param status the value for customer_care.status
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_care.feedback
     *
     * @return the value of customer_care.feedback
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public String getFeedback() {
        return feedback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_care.feedback
     *
     * @param feedback the value for customer_care.feedback
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setFeedback(String feedback) {
        this.feedback = feedback == null ? null : feedback.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_care.create_time
     *
     * @return the value of customer_care.create_time
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_care.create_time
     *
     * @param createTime the value for customer_care.create_time
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_care.manager_id
     *
     * @return the value of customer_care.manager_id
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public Integer getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_care.manager_id
     *
     * @param managerId the value for customer_care.manager_id
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setManagerId(Integer managerId) {
        this.managerId = managerId;
    }
}