package com.crm.wcx.entity;

import java.util.Date;

public class FollowUp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow_up.id
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow_up.time
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow_up.address
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow_up.general
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private String general;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow_up.remark
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow_up.content
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow_up.result
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private String result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow_up.customer_id
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private Integer customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow_up.manager_id
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private Integer managerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow_up.delete_status
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private Integer deleteStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow_up.document
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private String document;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow_up.id
     *
     * @return the value of follow_up.id
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow_up.id
     *
     * @param id the value for follow_up.id
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow_up.time
     *
     * @return the value of follow_up.time
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow_up.time
     *
     * @param time the value for follow_up.time
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow_up.address
     *
     * @return the value of follow_up.address
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow_up.address
     *
     * @param address the value for follow_up.address
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow_up.general
     *
     * @return the value of follow_up.general
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public String getGeneral() {
        return general;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow_up.general
     *
     * @param general the value for follow_up.general
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setGeneral(String general) {
        this.general = general == null ? null : general.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow_up.remark
     *
     * @return the value of follow_up.remark
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow_up.remark
     *
     * @param remark the value for follow_up.remark
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow_up.content
     *
     * @return the value of follow_up.content
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow_up.content
     *
     * @param content the value for follow_up.content
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow_up.result
     *
     * @return the value of follow_up.result
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow_up.result
     *
     * @param result the value for follow_up.result
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow_up.customer_id
     *
     * @return the value of follow_up.customer_id
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow_up.customer_id
     *
     * @param customerId the value for follow_up.customer_id
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow_up.manager_id
     *
     * @return the value of follow_up.manager_id
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public Integer getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow_up.manager_id
     *
     * @param managerId the value for follow_up.manager_id
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setManagerId(Integer managerId) {
        this.managerId = managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow_up.delete_status
     *
     * @return the value of follow_up.delete_status
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public Integer getDeleteStatus() {
        return deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow_up.delete_status
     *
     * @param deleteStatus the value for follow_up.delete_status
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow_up.document
     *
     * @return the value of follow_up.document
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public String getDocument() {
        return document;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow_up.document
     *
     * @param document the value for follow_up.document
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setDocument(String document) {
        this.document = document == null ? null : document.trim();
    }
}