package com.crm.wcx.entity;

import java.util.Date;

public class Linkman {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column linkman.id
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column linkman.name
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column linkman.position
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column linkman.office_phone
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private String officePhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column linkman.mobile_phone
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private String mobilePhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column linkman.birthday
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column linkman.sex
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column linkman.remark
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column linkman.level
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column linkman.customer_id
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private Integer customerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column linkman.id
     *
     * @return the value of linkman.id
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column linkman.id
     *
     * @param id the value for linkman.id
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column linkman.name
     *
     * @return the value of linkman.name
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column linkman.name
     *
     * @param name the value for linkman.name
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column linkman.position
     *
     * @return the value of linkman.position
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column linkman.position
     *
     * @param position the value for linkman.position
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column linkman.office_phone
     *
     * @return the value of linkman.office_phone
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public String getOfficePhone() {
        return officePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column linkman.office_phone
     *
     * @param officePhone the value for linkman.office_phone
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setOfficePhone(String officePhone) {
        this.officePhone = officePhone == null ? null : officePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column linkman.mobile_phone
     *
     * @return the value of linkman.mobile_phone
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column linkman.mobile_phone
     *
     * @param mobilePhone the value for linkman.mobile_phone
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone == null ? null : mobilePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column linkman.birthday
     *
     * @return the value of linkman.birthday
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column linkman.birthday
     *
     * @param birthday the value for linkman.birthday
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column linkman.sex
     *
     * @return the value of linkman.sex
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column linkman.sex
     *
     * @param sex the value for linkman.sex
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column linkman.remark
     *
     * @return the value of linkman.remark
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column linkman.remark
     *
     * @param remark the value for linkman.remark
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column linkman.level
     *
     * @return the value of linkman.level
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column linkman.level
     *
     * @param level the value for linkman.level
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column linkman.customer_id
     *
     * @return the value of linkman.customer_id
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column linkman.customer_id
     *
     * @param customerId the value for linkman.customer_id
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }
}