package com.crm.wcx.entity;

public class LoggingEventException extends LoggingEventExceptionKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logging_event_exception.trace_line
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private String traceLine;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logging_event_exception.trace_line
     *
     * @return the value of logging_event_exception.trace_line
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public String getTraceLine() {
        return traceLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logging_event_exception.trace_line
     *
     * @param traceLine the value for logging_event_exception.trace_line
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setTraceLine(String traceLine) {
        this.traceLine = traceLine == null ? null : traceLine.trim();
    }
}