package com.crm.wcx.entity;

public class LoggingEventExceptionKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logging_event_exception.event_id
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private Long eventId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logging_event_exception.i
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private Short i;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logging_event_exception.event_id
     *
     * @return the value of logging_event_exception.event_id
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public Long getEventId() {
        return eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logging_event_exception.event_id
     *
     * @param eventId the value for logging_event_exception.event_id
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setEventId(Long eventId) {
        this.eventId = eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logging_event_exception.i
     *
     * @return the value of logging_event_exception.i
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public Short getI() {
        return i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logging_event_exception.i
     *
     * @param i the value for logging_event_exception.i
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setI(Short i) {
        this.i = i;
    }
}