package com.crm.wcx.entity;

public class LoggingEventProperty extends LoggingEventPropertyKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logging_event_property.mapped_value
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private String mappedValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logging_event_property.mapped_value
     *
     * @return the value of logging_event_property.mapped_value
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public String getMappedValue() {
        return mappedValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logging_event_property.mapped_value
     *
     * @param mappedValue the value for logging_event_property.mapped_value
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setMappedValue(String mappedValue) {
        this.mappedValue = mappedValue == null ? null : mappedValue.trim();
    }
}