package com.crm.wcx.entity;

public class SaleOpportunityWithBLOBs extends SaleOpportunity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_opportunity.general
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private String general;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_opportunity.description
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_opportunity.general
     *
     * @return the value of sale_opportunity.general
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public String getGeneral() {
        return general;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_opportunity.general
     *
     * @param general the value for sale_opportunity.general
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setGeneral(String general) {
        this.general = general == null ? null : general.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_opportunity.description
     *
     * @return the value of sale_opportunity.description
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_opportunity.description
     *
     * @param description the value for sale_opportunity.description
     *
     * @mbg.generated Thu Nov 08 12:19:13 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}